"""
utils/pdf_generator.py
======================
Creates professional PDF legal documents from letter text.
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib import colors


def build_pdf(letter_text: str, doc_type: str, tenant_name: str = "") -> bytes:
    """
    Wraps a plain text legal letter in a professional PDF layout.
    Returns PDF bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=1.1 * inch,
        rightMargin=1.1 * inch,
        topMargin=1.0 * inch,
        bottomMargin=1.0 * inch,
    )

    styles = getSampleStyleSheet()
    navy  = colors.HexColor("#0A1628")
    gold  = colors.HexColor("#C9A84C")
    slate = colors.HexColor("#64748B")
    body_color = colors.HexColor("#1E293B")

    title_style = ParagraphStyle(
        "AppTitle", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=14,
        textColor=navy, spaceAfter=2, alignment=1,
    )
    subtitle_style = ParagraphStyle(
        "AppSub", parent=styles["Normal"],
        fontName="Helvetica", fontSize=9,
        textColor=gold, spaceAfter=14, alignment=1,
        letterSpacing=1.5,
    )
    doc_type_style = ParagraphStyle(
        "DocType", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=13,
        textColor=navy, spaceAfter=20, alignment=1,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontName="Times-Roman", fontSize=11,
        leading=19, spaceAfter=8,
        textColor=body_color,
    )
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"],
        fontName="Helvetica", fontSize=8,
        textColor=slate, alignment=1,
    )

    story = [
        Paragraph("🏛️  LANDLORDAI", title_style),
        Paragraph("NYC PROPERTY MANAGEMENT  ·  LEGAL NOTICE", subtitle_style),
        HRFlowable(width="100%", thickness=2.5, color=gold, spaceAfter=16),
        Paragraph(doc_type.upper(), doc_type_style),
    ]

    for line in letter_text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 7))
        else:
            safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, body_style))

    story += [
        Spacer(1, 24),
        HRFlowable(width="100%", thickness=0.8, color=colors.HexColor("#E2E8F0"), spaceAfter=8),
        Paragraph(
            f"Generated by LandlordAI  ·  {datetime.now().strftime('%B %d, %Y')}  ·  "
            "For legal advice consult a licensed NYC attorney",
            footer_style,
        ),
    ]

    doc.build(story)
    return buf.getvalue()
